### ISSUE TITLE
Proposal to Contribute in Copywriting for this project 

### ISSUE THREAD

**Issue by frankremmy** [ShtHappens796/Accord#3]
Hello, I found your project and it's really amazing. I am a veteran copywriter and would love to contribute to your project by copywriting About Us, Contact Us, Privacy Policy etc. When the time is due. My question is will you review and merge it to your repository when it is done? 
Thanks

**Comment by ShtHappens796** [comment]
The project is still in early pre-alpha state, once the initial documentation and frontend/backend infrastructure is complete to a certain level, you will be free (and encouraged) to contribute to the documentation, any tutorials and the project's README. Whether the changes will be merged or not depends on the quality of the commits.

Additionally, having an about us page or a privacy policy defeats this purpose of having this project open-sourced, and it would only adhere to me hosting Accord on my own servers.

Thank you for showing interest on my project. It would greatly help if you starred the project and shared it to your peers. Marking the issue as resolved.
